apiVersion: v1
kind: Service
metadata:
  name: shortorial-backend-service
spec:
  selector:
    app: shortorial
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortorial-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortorial
      tier: backend
  template:
    metadata:
      labels:
        app: shortorial
        tier: backend
    spec:
      containers:
        - name: shortorial-backend
          image: dyckerkim/shortorial-backend:latest
          envFrom:
            - secretRef:
                name: shortorial-backend-secret
          # 네트워크로 데이터베이스에 접근하기 때문에 pv mount할 필요 없음
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
