# mysql init data 삽입할 때 한글 깨져서 초기 설정 필요
apiVersion: v1
kind: ConfigMap
metadata:
  name: shortorial-database-config
data:
  my.cnf: | # 줄바꿈을 유지하는 기호 -> 멀티라인 문자열 입력
    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4

    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
---
apiVersion: v1
kind: Service
metadata:
  name: shortorial-database-service
spec:
  selector:
    app: shortorial
    tier: database
  ports:
    - port: 3306 # 동일 포트 사용
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortorial-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortorial
      tier: database
  template:
    metadata:
      labels:
        app: shortorial
        tier: database
    spec:
      containers:
        - name: shortorial-database
          image: mysql:8.4
          envFrom:
            - secretRef: # mysql 인증 정보 보관
                name: shortorial-database-secret
          env:
            - name: MYSQL_DATABASE
              value: dance # 컨테이너 시작 전 데이터베이스 생성
          volumeMounts:
            - name: database-config-volume
              mountPath: /etc/mysql/my.cnf # /etc/mysql/my.cnf 파일(mysql 설정파일)을 shortorial-database-config로 설정
              subPath: my.cnf
            - name: shortorial-volume
              mountPath: /var/lib/mysql # /var/lib/mysql(mysql이 컨테이너에 데이터를 저장하는 경로)를 외부 pv에 연결하여 영구 저장
      volumes: # my.cnf는 환경변수가 아니라 !파일!이라서 볼륨으로 설정안하면 적용 못함
        - name: database-config-volume
          configMap: # config map으로 설정 파일을 읽음
            name: shortorial-database-config
        - name: shortorial-volume # pvc를 볼륨으로 설정
          persistentVolumeClaim:
            claimName: shortorial-pvc
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
