# mysql init data 삽입할 때 한글 깨져서 초기 설정 필요
apiVersion: v1
kind: ConfigMap
metadata:
  name: shortorial-database-config
data:
  my.cnf: | # 줄바꿈을 유지하는 기호 -> 멀티라인 문자열 입력
    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4

    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
---
apiVersion: v1
kind: Service
metadata:
  name: shortorial-database-service
spec:
  selector:
    app: shortorial
    tier: database
  ports:
    - port: 3306 # 동일 포트 사용
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortorial-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortorial
      tier: database
  template:
    metadata:
      labels:
        app: shortorial
        tier: database
    spec:
      containers:
        - name: shortorial-database
          image: mysql:8.4
          env:
            - name: MYSQL_DATABASE
              value: dance
          volumeMounts:
            - name: database-config-volume
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
            - name: shortorial-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: database-config-volume
        - name: shortorial-volume
          persistentVolumeClaim:
            claimName: shortorial-pvc
