apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shortorial-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: shortorial-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06be5065024f2b8b9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shortorial-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: shortorial-efs-sc
