name: Backend CI # develop에 모인 코드들로 빌드 시도

on:
  push:
    branches: ["release-*"]
    paths-ignore:
      - "front/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 액션으로 체크아웃
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub # 도커 허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image # 도커 이미지 빌드 & 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}/shortorial-backend:4 .
          docker push ${{ secrets.DOCKER_REPO }}/your-app-name:4
          docker push ${{ secrets.DOCKER_REPO }}/your-app-name:latest
