name: Backend CI # develop에 모인 코드들로 빌드 시도

on:
  pull_request:
    branches: ["develop"]
    paths-ignore:
      - "front/**" # 프론트 파일 변경은 감지 안 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 액션으로 체크아웃
        uses: actions/checkout@v4

      - name: Set up JDK 17 # 자바 설치
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin" # open jdk 배포판

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle # 빌드 수행
        working-directory: back/sleep
        run: ./gradlew build
        env: # 깃헙 secret에 저장한 환경 변수 활용
          MYSQL_URL: ${{ secrets.MYSQL_URL_TEST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER_TEST }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD_TEST }}
          REDIS_URL: ${{ secrets.REDIS_URL_TEST }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JWT_SECRET: ${{secrets.JWT_SECRET_TEST}}
          VITE_HOME_URL: ${{ secrets.VITE_HOME_URL_TEST }}
