name: Backend CI # develop에 모인 코드들로 빌드 시도

on:
  push:
    branches: ["release-*"]
    paths-ignore:
      - "front/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 액션으로 체크아웃
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub # 도커 허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image # Docker 이미지 빌드 및 푸시 # 커밋 번호 이용하면 오류났을 때 그 번호로 쉽게 돌아갈 수 있음
        run: |
          cd back/sleep
          cd back/sleep
          docker buildx build -t ${{ secrets.DOCKER_REPO }}/shortorial-backend:${{ github.sha }} --push .
          docker buildx build -t ${{ secrets.DOCKER_REPO }}/shortorial-backend:latest --push .
