name: Backend CI # develop에 모인 코드들로 빌드 시도

on:
  push:
    branches: ["release-*"]
    paths-ignore:
      - "front/**"

# 깃헙 토큰 권한 생성
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 액션으로 체크아웃
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub # 도커 허브 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸시
      # 태그를 커밋 번호로 하면 오류났을 때 그 번호로 쉽게 돌아갈 수 있음
      # buildx 방식으로 build하면 더 빠름
      - name: Build and Push Docker Image
        run: |
          cd back/sleep
          docker buildx build -t ${{ secrets.DOCKER_REPO }}/shortorial-backend:${{ github.sha }} --push .
          docker buildx build -t ${{ secrets.DOCKER_REPO }}/shortorial-backend:latest --push .

      # aws에 github actions용 oidc, role 생성
      # describe cluster/node, list cluster/node, sts assume 정책 추가해서 연결
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsEKSRole

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-northeast-2 --name shortorial

      #  eks에 최신 이미지 반영
      - name: Deploy
        run: kubectl rollout restart deployment/shortorial-backend-deployment
