name: Backend CI # develop에 모인 코드들로 빌드 시도

on:
  pull_request:
    branches: ["develop"]
    paths-ignore:
      - "front/**" # 프론트엔드 코드 변경은 무시

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 액션으로 체크아웃
        uses: actions/checkout@v4

      - name: Set up JDK 17 # 자바 설치
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin" # open jdk 배포판

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle # 빌드 수행
        working-directory: back/sleep
        run: | # 여러 줄이면 추가
          cd back/sleep  
          ./gradlew build -x test
        env: # 깃헙 secret에 저장한 환경 변수 활용
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
