name: Frontend CI

on:
  push:
    branches: ["develop"]
    paths-ignore:
      - "back/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # 코드 체크아웃
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clean npm cache # 캐시 정리
        run: |
          cd front
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install Dependencies # npm install을 가볍게하는 npm ci
        run: |
          cd front
          npm ci

      - name: Build Project
        run: |
          cd front 
          npm run build
